name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.numeuniq.outputs.script-file }}    
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Publish JS filename
        id: numeuniq
        run: find *.html -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            index.html
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            index.html          
