name: push workflow # workflow name
on: push # workflow trigger
jobs:
  push-job:
    runs-on: ubuntu-latest # runner
    steps: 
      - name: Get code
        uses: actions/checkout@v3 
      - name: Setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 18     
      # - name: Npm install dependencies
      #   run: npm ci    
      # - name: Run npm test
      #   run: npm test     
# npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2024-03-04T20_30_37_928Z-debug-0.log