name: push workflow # workflow name
on: push # workflow trigger
jobs:
  push-job:
    runs-on: ubuntu-latest # runner
    steps: 
      - name: Get code
        uses: actions/checkout@v3 
      - name: Setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16     
      - name: Npm install dependencies
        run: npm ci         